#!/bin/bash
source $HOME/scripts/lib/term-cfns

if [[ "`issess 0:YT`" != true ]]; then
  mkwin 0 YT "TERM=screen-256color lf -config <(cat $HOME/.config/lf/lfrc; echo set ratios 1) $HOME/storage/shared/Download/YTDLnis/Video/"
else
  selwin 0 YT
  selsess 0
fi
