#!/bin/bash
source $HOME/scripts/lib/term-cfns

mkwin "`tmux display-message -p '#S'`" YT "TERM=screen-256color lf -config <(cat $HOME/.config/lf/lfrc; echo set ratios 1) $HOME/storage/shared/Download/YTDLnis/Video/"
